#!/usr/bin/env python

from __future__ import division

__author__ = "Daniel McDonald"
__copyright__ = "Copyright 2011, The tax2tree project"
__credits__ = ["Daniel McDonald"]
__license__ = "GPL"
__version__ = "1.0"
__maintainer__ = "Daniel McDonald"
__email__ = "mcdonadt@colorado.edu"
__status__ = "Development"

from optparse import make_option
from cogent.util.misc import parse_command_line_parameters
from cogent.parse.tree import DndParser
from t2t.util import reroot
import os

script_info = {}
script_info['brief_description'] = "reroot script"
script_info['script_description'] = "reroot tree based on a set of tipnames"
script_info['script_usage'] = [("","","")]
script_info['output_description']= ""
script_info['required_options']=[make_option('--input','-i',dest='input',\
                    help='Input tree'),
              make_option('--tipnames','-t',dest='tipnames',\
                    help='File containing tipnames'),
              make_option('--output','-o', dest='output',\
                    help='Output directory')]

script_info['version'] = __version__

def main():
    option_parser, opts, args = parse_command_line_parameters(**script_info)

    if not opts.input:
        option_parser.error("No input tree specified!")

    if not opts.tipnames:
        option_parser.error("No tipnames specified!")

    if not opts.output:
        option_parser.error("No output file specified!")

    if os.path.exists(opts.output):
        option_parser.error("Output file already exists!")

    tipnames = set([l.strip() for l in open(opts.tipnames)])
    tree = DndParser(open(opts.input))
    rerooted = reroot(tree, tipnames)
    
    f = open(opts.output,'w')
    f.write(rerooted.getNewick(with_distances=True))
    f.close()

if __name__ == '__main__':
    main()
