name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'
    - name: Install dependencies
      run: bash -l {0}
        conda create -y -n test-env python=3.8 pip click scikit-bio flake8 pytest
        conda activate test-env
        pip install iow
        pip install -e . --no-deps
    - name: Lint with flake8
      run: bash -l {0}
        conda activate test-env
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: bash -l {0}
        conda activate test-env
        pytest
